spring:
  datasource:
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
  flyway: # TODO: delete after creating specific version table on the prod
    baseline-version: 1

logging:
  level:
    org.springframework.web.servlet: debug
    com.banew.cw2025_backend: error

secret.decoder_key: ${SECRET_DECODE_KEY}