spring:
  jpa:
    properties:
      hibernate:
        bytecode:
          provider: bytebuddy
          use_reflection_optimizer: false
  application:
    name: cw2025_backend
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

token_lifetime: 7
