spring:
  datasource:
    username: postgres
    password: Shift2201
    url: jdbc:postgresql://localhost:5432/cs2025_db
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate:
      SQL: trace
      engine.internal.StatisticalLoggingSessionEventListener: error

secret.decoder_key: DICKABOABOSARle;rkewjefreljfjrejkhrewghrekhgreherkhnremnrekjnakjhkjnardnhvdksrjgvhaekgjhsedklugvhsdrkgj