spring:
  application:
    name: cw2025_backend
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web.servlet: DEBUG

token_lifetime: 7
